-- 1. Create Enum Types first
CREATE TYPE post_type_enum AS ENUM ('DISCUSSION', 'NEWS', 'PODCAST');
CREATE TYPE post_category_enum AS ENUM ('DISCUSSION', 'NEWS');

-- 2. Create Tables and Views

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    is_upn_member BOOLEAN DEFAULT FALSE NOT NULL,
    profile_picture VARCHAR(255) DEFAULT 'https://cozwvhycpghwqquezuxs.supabase.co/storage/v1/object/public/store/default_avatar.svg?t=2024-03-18T06%3A44%3A56.263Z',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    followed_authors JSONB DEFAULT '[]'::jsonb,
    role VARCHAR(255) DEFAULT 'user'
);

CREATE VIEW admins AS
SELECT id,
    email,
    username,
    name,
    password,
    is_upn_member,
    profile_picture,
    created_at,
    followed_authors,
    role
FROM users
WHERE role = 'USERADMIN' OR role = 'ITADMIN';

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author BIGINT,
    content TEXT,
    posttype post_type_enum,
    postid BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    podcastid BIGINT
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    author BIGINT,
    pictures JSONB DEFAULT '[]'::jsonb,
    likes BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    views BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    category post_category_enum
);

CREATE VIEW discussions AS
SELECT id,
    title,
    content,
    author,
    pictures,
    likes,
    comments,
    views,
    created_at,
    category
FROM posts
WHERE category = 'DISCUSSION';

CREATE VIEW news AS
SELECT id,
    title,
    content,
    author,
    pictures,
    likes,
    comments,
    views,
    created_at,
    category
FROM posts
WHERE category = 'NEWS';

CREATE TABLE podcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    author BIGINT,
    thumbnail VARCHAR(255),
    duration BIGINT DEFAULT 0,
    views BIGINT DEFAULT 0,
    likes BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    url TEXT
);

CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid BIGINT,
    settings JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);